name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Frontend CI
      - name: Install Frontend dependencies
        working-directory: Frontend
        run: npm install

      - name: Run Frontend lint
        working-directory: Frontend
        run: npm run lint

      - name: Run Frontend tests
        working-directory: Frontend
        run: npm run test

      # Backend Functions CI
      - name: Install Backend Functions dependencies
        working-directory: Backend/functions
        run: npm install

      - name: Run Backend Functions lint
        working-directory: Backend/functions
        run: npm run lint
