name: CI/CD for React Native

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd app && yarn install

      - name: Run ESLint (Code Linting)
        run: cd app && yarn lint

      - name: Run Jest Tests
        run: yarn test

      - name: Build Android App
        run: cd android && ./gradlew assembleRelease
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Clean Yarn Cache
        run: yarn cache clean

